### ISSUE TITLE
请问下怎么还原出文件名？

### ISSUE THREAD

**Issue by JoythanYu** [r00t1900/tencent-edu-wrapper#8]
批量一次下载了300多个.m3u8.sqlite文件，解密成.ts文件。不知道文件名，也不知道顺序，没办法学习

**Comment by r00t1900** [comment]
文件名信息不在这里面的，所以暂时无法还原，要还原文件名需要其他信息辅助。如果你有想法，请告诉我，谢谢~



在 2020-04-23 19:13:14，"Ethan" <notifications@github.com> 写道：

批量一次下载了300多个.m3u8.sqlite文件，解密成.ts文件。不知道文件名，也不知道顺序，没办法学习

**Comment by JoythanYu** [comment]
已经找到了 在OfflineDownlaodDB中

**Comment by caifenglin** [comment]
> 已经找到了 在OfflineDownlaodDB中

你好，我也是不知道文件名，没法学习，请问OfflineDownlaodDB是什么意思

**Comment by r00t1900** [comment]
字面上，OfflineDownlaodDB是离线下载数据库的意思。

**Comment by JoythanYu** [comment]
打开表看下字段名称，里面直接有文件名称。（新版本不确定）



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月23日(星期天) 上午6:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [r00t1900/tencent-edu-wrapper] 请问下怎么还原出文件名？ (#8)





  
已经找到了 在OfflineDownlaodDB中
  
你好，我也是不知道文件名，没法学习，请问OfflineDownlaodDB是什么意思
